### ISSUE TITLE
Surgical removal of a limb causes instant sepsis and broken ribs

### ISSUE THREAD

**Issue by ErikNielsen2014** [Aurorastation/Aurora#504] opened 2015-04-20 03:59 UTC
I was surgically removing someone's prosthetic arm with a surgical saw. They were under anesthetic. When the limb was surgically removed, this caused instant massive brute damage to the chest as well as breaking a bone, despite me not once touching the chest. Then, I surgically reattached a replacement prosthetic limb. I called medical. The patient was, for some reason, going into shock. So apparently it caused massive brute damage. They died of sepsis within minutes.

I refuse to believe that the game mechanics are meant to be so mind-numbingly stupid, so I'm making a bug report for this.

**Comment by Jamini** [comment] 2015-04-30 14:28
I believe this may be caused by some Aurora-specific limb loss code? I've not seen this issue on other servers generally.

**Comment by skull132** [comment] 2015-05-29 21:52
I think I'm basically going to have to import newest Bay organ + surgery code, partially in prep for the Biologist position anyways. So, should be tending to this next week.

**Comment by skull132** [comment] 2015-06-03 13:57
Fixed now. Reference the pulls and commits above.

**Closed by skull132** 2015-06-03 13:57 UTC
Labels: Bug
