### ISSUE TITLE
AI holopad doesn't transmit or receive

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora#516] opened 2015-04-25 23:32 UTC
I'm not certain what causes this, it seems to work for about a minute, then it stops transmitting or receiving anything aid in the area. It's happened with every AI holopad I've tested with so far.

**Comment by skull132** [comment] 2015-05-28 17:45
Unable to replicate at this time. May have been fixed inbetween now and then; or the circumstances caused by something like missing atmos.

**Closed** 2015-05-31 20:15 UTC
Labels: Unable to Replicate
